<?php
/**
 * Plugin Name:       WordPress MCP Ability Suite
 * Plugin URI:        https://github.com/als141/wordpress-mcp-ability-plugin
 * Description:       Expose WordPress content operations to AI agents via Model Context Protocol (MCP) with app authentication support.
 * Version:           1.2.0
 * Author:            als141
 * Author URI:        https://profiles.wordpress.org/als141/
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       wordpress-mcp-ability-suite
 * Domain Path:       /languages
 * Requires at least: 6.0
 * Requires PHP:      8.1
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Loader: prefer Jetpack Autoloader, fallback to Composer autoload.
 */
$jetpack_autoloader  = __DIR__ . '/vendor/autoload_packages.php';
$composer_autoloader = __DIR__ . '/vendor/autoload.php';
if ( file_exists( $jetpack_autoloader ) ) {
	require_once $jetpack_autoloader;
} elseif ( file_exists( $composer_autoloader ) ) {
	require_once $composer_autoloader;
}

// Ensure MCP Adapter classes are autoloadable even without Composer/Jetpack autoloader.
if ( ! function_exists( 'wp_mcp_bootstrap_adapter' ) ) {
	function wp_mcp_bootstrap_adapter() {
		if ( class_exists( '\\WP\\MCP\\Core\\McpAdapter', false ) ) {
			return;
		}

		$mcp_adapter_dir = __DIR__ . '/vendor/wordpress/mcp-adapter/src';
		$mcp_entry       = $mcp_adapter_dir . '/Core/McpAdapter.php';

		if ( ! file_exists( $mcp_entry ) ) {
			return;
		}

		if ( version_compare( PHP_VERSION, '8.0', '<' ) ) {
			add_action( 'admin_notices', static function () {
				if ( function_exists( 'wp_admin_notice' ) ) {
					wp_admin_notice(
						__( 'MCP Adapter を使用するには PHP 8.0 以上が必要です。', 'wp-mcp-suite' ),
						array(
							'type'    => 'warning',
							'dismiss' => false,
						)
					);
				} else {
					echo '<div class="notice notice-warning"><p>';
					echo esc_html__( 'MCP Adapter を使用するには PHP 8.0 以上が必要です。', 'wp-mcp-suite' );
					echo '</p></div>';
				}
			} );
			return;
		}

		spl_autoload_register( static function ( $class ) use ( $mcp_adapter_dir ) {
			$prefix = 'WP\\MCP\\';
			if ( 0 !== strpos( $class, $prefix ) ) {
				return;
			}
			$relative = substr( $class, strlen( $prefix ) );
			$path     = $mcp_adapter_dir . '/' . str_replace( '\\', '/', $relative ) . '.php';
			if ( file_exists( $path ) ) {
				require_once $path;
			}
		} );

		// Force-load the main adapter class once to verify autoloading works.
		require_once $mcp_entry;

		if ( ! class_exists( '\\WP\\MCP\\Core\\McpAdapter', false ) ) {
			// As a last resort, eagerly load all MCP Adapter source files.
			$dir_iter = new RecursiveDirectoryIterator( $mcp_adapter_dir, RecursiveDirectoryIterator::SKIP_DOTS );
			$iter = new RecursiveIteratorIterator( $dir_iter );
			foreach ( $iter as $file ) {
				$path = $file->getPathname();
				if ( substr( $path, -4 ) === '.php' ) {
					require_once $path;
				}
			}
		}
	}
}

wp_mcp_bootstrap_adapter();

// Abilities API is bundled but not autoloaded; load explicitly.
$abilities_bootstrap = __DIR__ . '/vendor/wordpress/abilities-api/abilities-api.php';
if ( file_exists( $abilities_bootstrap ) ) {
	require_once $abilities_bootstrap;
}

// Ensure Abilities API loads early via MU plugin.
register_activation_hook( __FILE__, static function () use ( $abilities_bootstrap ) {
	$mu_dir = WP_CONTENT_DIR . '/mu-plugins';
	if ( ! file_exists( $mu_dir ) && ! wp_mkdir_p( $mu_dir ) ) {
		return;
	}

	$loader_path = $mu_dir . '/abilities-api-loader.php';

	$loader_code = <<<PHP
<?php
// Auto-generated by WordPress MCP Ability Suite to load bundled Abilities API early.
// This file is safe to keep even if the plugin is deactivated.
\$abilities_file = '{$abilities_bootstrap}';
if ( file_exists( \$abilities_file ) ) {
	require_once \$abilities_file;
}
PHP;

	file_put_contents( $loader_path, $loader_code );
} );

register_deactivation_hook( __FILE__, static function () {
	$loader_path = WP_CONTENT_DIR . '/mu-plugins/abilities-api-loader.php';
	if ( file_exists( $loader_path ) ) {
		unlink( $loader_path );
	}
} );

if ( ! function_exists( 'wp_register_ability' ) ) {
	add_action( 'admin_notices', static function () {
		wp_admin_notice(
			__( 'Abilities API が見つかりません。wordpress/abilities-api をインストールしてください。', 'wp-mcp-suite' ),
			array(
				'type'    => 'error',
				'dismiss' => false,
			)
		);
	} );
	return;
}

if ( class_exists( '\\WP\\MCP\\Core\\McpAdapter' ) ) {
	\WP\MCP\Core\McpAdapter::instance();
}

if ( ! defined( 'WP_MCP_PLUGIN_VERSION' ) ) {
	define( 'WP_MCP_PLUGIN_VERSION', '1.2.0' );
}
if ( ! defined( 'WP_MCP_ABILITY_PREFIX' ) ) {
	define( 'WP_MCP_ABILITY_PREFIX', 'wp-mcp' );
}

require_once __DIR__ . '/includes/helpers.php';
require_once __DIR__ . '/includes/abilities/categories.php';
require_once __DIR__ . '/includes/abilities/tools.php';
require_once __DIR__ . '/includes/abilities/resources.php';
require_once __DIR__ . '/includes/abilities/prompts.php';

// Load SaaS Authentication classes.
require_once __DIR__ . '/includes/saas-auth/class-saas-auth-provider.php';
require_once __DIR__ . '/includes/saas-auth/class-api-key-manager.php';
require_once __DIR__ . '/includes/saas-auth/class-oauth-metadata.php';
require_once __DIR__ . '/includes/saas-auth/class-admin-settings.php';

// Initialize SaaS Authentication components.
WP_MCP\SaaS_Auth\SaaS_Auth_Provider::instance();
WP_MCP\SaaS_Auth\API_Key_Manager::instance();
WP_MCP\SaaS_Auth\OAuth_Metadata::instance();
WP_MCP\SaaS_Auth\Admin_Settings::instance(); // Must be initialized outside is_admin() for REST routes.

require_once __DIR__ . '/includes/mcp-server.php';

/**
 * Plugin activation callback.
 */
function wp_mcp_activate_plugin(): void {
	// Flush rewrite rules for .well-known endpoints.
	WP_MCP\SaaS_Auth\OAuth_Metadata::flush_rewrite_rules();

	// Auto-enable SaaS authentication with sensible defaults.
	$auth_provider = WP_MCP\SaaS_Auth\SaaS_Auth_Provider::instance();
	$settings      = $auth_provider->get_settings();

	if ( ! $settings['enabled'] ) {
		$settings['enabled']             = true;
		$settings['require_https']       = is_ssl();
		$settings['rate_limit_enabled']  = false;
		$settings['audit_log_enabled']   = true;
		$auth_provider->update_settings( $settings );
	}
}
register_activation_hook( __FILE__, 'wp_mcp_activate_plugin' );
