<?php
/**
 * Plugin Name: Readonly Ability Sample (MCP)
 * Description: サンプルの読み取り専用アビリティを Abilities API と MCP Adapter で公開します。
 * Version: 0.2.0
 * Author: Example
 * License: GPL-2.0-or-later
 */

/**
 * ローダー: Jetpack Autoloader を優先し、なければ Composer の autoload を使う。
 */
$jetpack_autoloader = __DIR__ . '/vendor/autoload_packages.php';
$composer_autoloader = __DIR__ . '/vendor/autoload.php';
if ( file_exists( $jetpack_autoloader ) ) {
	require_once $jetpack_autoloader;
} elseif ( file_exists( $composer_autoloader ) ) {
	require_once $composer_autoloader;
}

// Composer オートロードだけでは Abilities API は読み込まれないため、同梱版を明示的にロードする。
$abilities_bootstrap = __DIR__ . '/vendor/wordpress/abilities-api/abilities-api.php';
if ( file_exists( $abilities_bootstrap ) ) {
	require_once $abilities_bootstrap;
}

// --- 依存を必ず先に読み込ませるための MU プラグイン設置 ---
register_activation_hook( __FILE__, static function () use ( $abilities_bootstrap ) {
	$mu_dir = WP_CONTENT_DIR . '/mu-plugins';
	if ( ! file_exists( $mu_dir ) && ! wp_mkdir_p( $mu_dir ) ) {
		return;
	}

	$loader_path = $mu_dir . '/abilities-api-loader.php';
	$plugin_path = plugin_dir_path( __FILE__ );

	$loader_code = <<<PHP
<?php
// Auto-generated by Readonly Ability Sample (MCP) to load bundled Abilities API early.
// This file is safe to keep even if the plugin is deactivated.
$abilities_file = '{$abilities_bootstrap}';
if ( file_exists( $abilities_file ) ) {
	require_once $abilities_file;
}
PHP;

	file_put_contents( $loader_path, $loader_code );
} );

register_deactivation_hook( __FILE__, static function () {
	$loader_path = WP_CONTENT_DIR . '/mu-plugins/abilities-api-loader.php';
	if ( file_exists( $loader_path ) ) {
		unlink( $loader_path );
	}
} );

// 依存チェック。Abilities API が無ければ何もしない。
if ( ! function_exists( 'wp_register_ability' ) ) {
	add_action( 'admin_notices', static function () {
		wp_admin_notice(
			__( 'Abilities API が見つかりません。wordpress/abilities-api をインストールしてください。', 'readonly-ability' ),
			array(
				'type'    => 'error',
				'dismiss' => false,
			)
		);
	} );
	return;
}

// MCP Adapter の存在チェック（なくてもアビリティ登録は行う）。
if ( class_exists( '\\WP\\MCP\\Core\\McpAdapter' ) ) {
	\WP\MCP\Core\McpAdapter::instance();
}

/**
 * アビリティ登録: 公開投稿の最新 5 件を返す読み取り専用ツール。
 */
add_action( 'wp_abilities_api_init', static function () {
	wp_register_ability( 'readonly-plugin/get-latest-posts', array(
		'label' => 'Get Latest Posts (Readonly)',
		'description' => '最新の公開投稿タイトルと URL を返します。',
		'category' => 'site',
			'input_schema' => array(
				'type' => 'object',
				'properties' => array(
					'limit' => array(
						'type' => 'integer',
						'description' => '取得件数 (1-20)',
						'default' => 5,
						'minimum' => 1,
						'maximum' => 20,
					),
				),
			),
			'output_schema' => array(
				'type' => 'array',
				'items' => array(
					'type' => 'object',
					'properties' => array(
						'ID' => array( 'type' => 'integer' ),
						'title' => array( 'type' => 'string' ),
						'permalink' => array( 'type' => 'string' ),
						'date' => array( 'type' => 'string' ),
					),
				),
			),
			'meta' => array(
				'show_in_rest' => true,
				'mcp' => array(
					'public' => true,
					'type'   => 'tool',
				),
			),
			'permission_callback' => static function () {
			return current_user_can( 'read' );
		},
		'execute_callback' => static function ( $input ) {
			$limit = isset( $input['limit'] ) ? (int) $input['limit'] : 5;
			$limit = max( 1, min( 20, $limit ) );

			$posts = get_posts( array(
				'numberposts' => $limit,
				'post_status' => 'publish',
				'orderby' => 'date',
				'order' => 'DESC',
			) );

			return array_map( static function ( $post ) {
				return array(
					'ID' => (int) $post->ID,
					'title' => get_the_title( $post ),
					'permalink' => get_permalink( $post ),
					'date' => get_the_date( DATE_ATOM, $post ),
				);
			}, $posts );
		},
	) );
} );

/**
 * 追加能力カテゴリの登録（先に実行しておく）。
 */
add_action( 'wp_abilities_api_init', static function () {
	wp_register_ability_category(
		'seo',
		array(
			'label'       => 'SEO',
			'description' => 'SEO 解析や内部リンク支援のための能力。',
		)
	);
} );

/**
 * 軽量記事リストを返す能力。
 */
add_action( 'wp_abilities_api_init', static function () {
	wp_register_ability( 'readonly-plugin/list-articles', array(
		'label'       => 'List Articles (Paged)',
		'description' => 'ページング可能な記事リストを返します。省略やトリミングは行いません。',
		'category'    => 'site',
		'input_schema' => array(
			'type'       => 'object',
			'properties' => array(
				'limit'      => array(
					'type'    => 'integer',
					'minimum' => 1,
					'maximum' => 20,
					'default' => 5,
					'description' => '取得件数 (1-20)',
				),
				'offset'     => array(
					'type'        => 'integer',
					'minimum'     => 0,
					'default'     => 0,
					'description' => 'スキップする件数。0,20,40... で全件をページング取得可能。',
				),
				'fields'     => array(
					'type'        => 'array',
					'uniqueItems' => true,
					'items'       => array(
						'type' => 'string',
						'enum' => array( 'id', 'title', 'slug', 'permalink', 'date', 'excerpt', 'author' ),
					),
					'description' => '含めるフィールド。空の場合は id,title,permalink,date を返す。',
				),
				'order'      => array(
					'type'        => 'string',
					'enum'        => array( 'ASC', 'DESC' ),
					'default'     => 'DESC',
				),
				'orderby'    => array(
					'type'        => 'string',
					'enum'        => array( 'date', 'modified', 'title', 'id' ),
					'default'     => 'date',
				),
				'with_total' => array(
					'type'        => 'boolean',
					'default'     => false,
					'description' => 'true のとき総件数 total を含める。',
				),
			),
			'required' => array(),
		),
		'output_schema' => array(
			'type'       => 'object',
			'properties' => array(
				'items' => array(
					'type'  => 'array',
					'items' => array( 'type' => 'object' ),
				),
				'total' => array(
					'type' => 'integer',
				),
			),
		),
		'meta' => array(
			'show_in_rest' => true,
			'mcp'          => array(
				'public' => true,
				'type'   => 'tool',
			),
		),
		'permission_callback' => static function () {
			return current_user_can( 'read' );
		},
		'execute_callback' => static function ( $input ) {
			$limit      = isset( $input['limit'] ) ? (int) $input['limit'] : 5;
			$offset     = isset( $input['offset'] ) ? max( 0, (int) $input['offset'] ) : 0;
			$order      = isset( $input['order'] ) && in_array( strtoupper( $input['order'] ), array( 'ASC', 'DESC' ), true ) ? strtoupper( $input['order'] ) : 'DESC';
			$orderby    = isset( $input['orderby'] ) && in_array( $input['orderby'], array( 'date', 'modified', 'title', 'id' ), true ) ? $input['orderby'] : 'date';
			$fields_raw = isset( $input['fields'] ) && is_array( $input['fields'] ) ? $input['fields'] : array();

			// デフォルトフィールド。
			$default_fields = array( 'id', 'title', 'permalink', 'date' );
			$fields         = array_values( array_unique( ! empty( $fields_raw ) ? $fields_raw : $default_fields ) );

			$q = new \WP_Query(
				array(
					'post_type'           => 'post',
					'post_status'         => 'publish',
					'posts_per_page'      => $limit,
					'offset'              => $offset,
					'orderby'             => $orderby,
					'order'               => $order,
					'no_found_rows'       => empty( $input['with_total'] ) ? true : false,
					'ignore_sticky_posts' => true,
				)
			);

			$items = array();
			while ( $q->have_posts() ) {
				$q->the_post();
				$post = get_post();
				$row  = array();
				foreach ( $fields as $field ) {
					switch ( $field ) {
						case 'id':
							$row['id'] = $post->ID;
							break;
						case 'title':
							$row['title'] = get_the_title( $post );
							break;
						case 'slug':
							$row['slug'] = $post->post_name;
							break;
						case 'permalink':
							$row['permalink'] = get_permalink( $post );
							break;
						case 'date':
							$row['date'] = get_the_date( DATE_ATOM, $post );
							break;
						case 'excerpt':
							$row['excerpt'] = get_the_excerpt( $post );
							break;
						case 'author':
							$author         = get_userdata( $post->post_author );
							$row['author']  = $author ? $author->display_name : '';
							break;
					}
				}
				$items[] = $row;
			}
			wp_reset_postdata();

			$result = array( 'items' => $items );
			if ( ! empty( $input['with_total'] ) ) {
				$result['total'] = (int) $q->found_posts;
			}

			return $result;
		},
	) );
} );

/**
 * 記事詳細を返す能力（HTML本文も返せる）。
 */
add_action( 'wp_abilities_api_init', static function () {
	wp_register_ability( 'readonly-plugin/get-article', array(
		'label'       => 'Get Article (Detailed)',
		'description' => 'ID またはスラッグで記事詳細を取得します。HTML本文も返せます。',
		'category'    => 'site',
		'input_schema' => array(
			'type'       => 'object',
			'properties' => array(
				'id'             => array( 'type' => 'integer' ),
				'slug'           => array( 'type' => 'string' ),
				'include_fields' => array(
					'type'        => 'array',
					'uniqueItems' => true,
					'items'       => array(
						'type' => 'string',
						'enum' => array( 'content', 'excerpt', 'categories', 'tags', 'featured_image', 'meta' ),
					),
					'description' => '追加で含めるフィールド。常に id,title,permalink,date は返します。',
				),
			),
			'oneOf' => array(
				array( 'required' => array( 'id' ) ),
				array( 'required' => array( 'slug' ) ),
			),
		),
		'output_schema' => array(
			'type'       => 'object',
			'properties' => array(
				'article' => array( 'type' => 'object' ),
			),
			'required' => array( 'article' ),
		),
		'meta' => array(
			'show_in_rest' => true,
			'mcp'          => array(
				'public' => true,
				'type'   => 'tool',
			),
		),
		'permission_callback' => static function () {
			return current_user_can( 'read' );
		},
		'execute_callback' => static function ( $input ) {
			$post = null;
			if ( isset( $input['id'] ) ) {
				$post = get_post( (int) $input['id'] );
			} elseif ( isset( $input['slug'] ) ) {
				$post = get_page_by_path( sanitize_title( $input['slug'] ), OBJECT, 'post' );
			}
			if ( ! $post ) {
				return new \WP_Error( 'not_found', '記事が見つかりません。' );
			}
			// 公開以外（下書き・非公開など）は、閲覧権限のあるユーザーのみ許可する。
			if ( 'publish' !== $post->post_status && ! current_user_can( 'read_post', $post->ID ) ) {
				return new \WP_Error( 'forbidden', 'この記事を閲覧する権限がありません。' );
			}

			$include = isset( $input['include_fields'] ) && is_array( $input['include_fields'] ) ? $input['include_fields'] : array();

			$data = array(
				'id'        => $post->ID,
				'title'     => get_the_title( $post ),
				'permalink' => get_permalink( $post ),
				'date'      => get_the_date( DATE_ATOM, $post ),
			);

			if ( in_array( 'content', $include, true ) ) {
				$data['content'] = apply_filters( 'the_content', $post->post_content );
			}
			if ( in_array( 'excerpt', $include, true ) ) {
				$data['excerpt'] = $post->post_excerpt;
			}
			if ( in_array( 'categories', $include, true ) ) {
				$cats = get_the_category( $post );
				$data['categories'] = array_map(
					static function ( $c ) {
						return array( 'id' => $c->term_id, 'name' => $c->name, 'slug' => $c->slug );
					},
					$cats ?: array()
				);
			}
			if ( in_array( 'tags', $include, true ) ) {
				$tags = get_the_tags( $post->ID );
				$data['tags'] = array_map(
					static function ( $t ) {
						return array( 'id' => $t->term_id, 'name' => $t->name, 'slug' => $t->slug );
					},
					$tags ?: array()
				);
			}
			if ( in_array( 'featured_image', $include, true ) ) {
				$thumb_id = get_post_thumbnail_id( $post );
				if ( $thumb_id ) {
					$src               = wp_get_attachment_image_src( $thumb_id, 'full' );
					$data['featured_image'] = $src ? $src[0] : null;
				} else {
					$data['featured_image'] = null;
				}
			}
			if ( in_array( 'meta', $include, true ) ) {
				$data['meta'] = get_post_meta( $post->ID );
			}

			return array( 'article' => $data );
		},
	) );
} );

/**
 * SEO 簡易監査能力（AIOSEO の値は使用しない）。
 */
add_action( 'wp_abilities_api_init', static function () {
	wp_register_ability( 'readonly-plugin/seo-quick-audit', array(
		'label'       => 'SEO Quick Audit',
		'description' => 'タイトル長・見出し数などの簡易SEOチェックを返します（AIOSEO値は不使用）。',
		'category'    => 'seo',
		'input_schema' => array(
			'type'       => 'object',
			'properties' => array(
				'id'     => array( 'type' => 'integer' ),
				'slug'   => array( 'type' => 'string' ),
				'checks' => array(
					'type'        => 'array',
					'uniqueItems' => true,
					'items'       => array(
						'type' => 'string',
						'enum' => array( 'title_length', 'meta_desc_length', 'h1_count', 'word_count', 'image_alt_ratio', 'link_counts', 'readability_fk' ),
					),
				),
			),
			'oneOf' => array(
				array( 'required' => array( 'id' ) ),
				array( 'required' => array( 'slug' ) ),
			),
		),
		'output_schema' => array(
			'type'       => 'object',
			'properties' => array(
				'checks' => array( 'type' => 'object' ),
			),
			'required' => array( 'checks' ),
		),
		'meta' => array(
			'show_in_rest' => true,
			'mcp'          => array(
				'public' => true,
				'type'   => 'tool',
			),
		),
		'permission_callback' => static function () {
			return current_user_can( 'read' );
		},
		'execute_callback' => static function ( $input ) {
			$post = null;
			if ( isset( $input['id'] ) ) {
				$post = get_post( (int) $input['id'] );
			} elseif ( isset( $input['slug'] ) ) {
				$post = get_page_by_path( sanitize_title( $input['slug'] ), OBJECT, 'post' );
			}
			if ( ! $post || 'publish' !== $post->post_status ) {
				return new \WP_Error( 'not_found', '記事が見つかりません。' );
			}

			$checks = isset( $input['checks'] ) && is_array( $input['checks'] ) && ! empty( $input['checks'] )
				? $input['checks']
				: array( 'title_length', 'meta_desc_length', 'h1_count', 'word_count', 'image_alt_ratio', 'link_counts', 'readability_fk' );

			$content_html = apply_filters( 'the_content', $post->post_content );
			$content_text = wp_strip_all_tags( $content_html );

			$result = array();

			// Helper: status function.
			$status = static function ( $value, $ok_min, $ok_max = null ) {
				if ( null === $ok_max ) {
					return $value >= $ok_min ? 'ok' : 'warn';
				}
				if ( $value < $ok_min ) {
					return 'warn';
				}
				if ( $value > $ok_max ) {
					return 'warn';
				}
				return 'ok';
			};

			if ( in_array( 'title_length', $checks, true ) ) {
				$len               = mb_strlen( $post->post_title );
				$result['title_length'] = array(
					'value'  => $len,
					'status' => $status( $len, 30, 60 ),
				);
			}

			if ( in_array( 'meta_desc_length', $checks, true ) ) {
				$desc = $post->post_excerpt ? $post->post_excerpt : wp_trim_words( $content_text, 50, '' );
				$len  = mb_strlen( $desc );
				$result['meta_desc_length'] = array(
					'value'  => $len,
					'status' => $status( $len, 70, 160 ),
				);
			}

			if ( in_array( 'h1_count', $checks, true ) ) {
				preg_match_all( '/<h1\b[^>]*>/i', $content_html, $m );
				$count            = count( $m[0] );
				$result['h1_count'] = array(
					'value'  => $count,
					'status' => ( 1 === $count ) ? 'ok' : 'warn',
				);
			}

			if ( in_array( 'word_count', $checks, true ) ) {
				$words = str_word_count( wp_strip_all_tags( $content_html ) );
				$result['word_count'] = array(
					'value'  => $words,
					'status' => ( $words >= 300 ) ? 'ok' : 'warn',
				);
			}

			if ( in_array( 'image_alt_ratio', $checks, true ) ) {
				preg_match_all( '/<img\b[^>]*>/i', $content_html, $imgs );
				$all   = count( $imgs[0] );
				$with  = 0;
				if ( $all > 0 ) {
					foreach ( $imgs[0] as $img_tag ) {
						if ( preg_match( '/alt\\s*=\\s*\"[^\"]+\"/i', $img_tag ) || preg_match( "/alt\\s*=\\s*'[^']+'/i", $img_tag ) ) {
							++$with;
						}
					}
				}
				$ratio = $all > 0 ? $with / $all : 1;
				$result['image_alt_ratio'] = array(
					'value'  => $ratio,
					'status' => ( $ratio >= 0.8 ) ? 'ok' : 'warn',
				);
			}

			if ( in_array( 'link_counts', $checks, true ) ) {
				preg_match_all( '/<a\b[^>]*href=[\"\']([^\"\']+)[\"\'][^>]*>/i', $content_html, $links );
				$internal = 0;
				$external = 0;
				$home     = home_url();
				foreach ( $links[1] as $href ) {
					if ( str_starts_with( $href, $home ) || str_starts_with( $href, '/' ) ) {
						++$internal;
					} else {
						++$external;
					}
				}
				$result['link_counts'] = array(
					'value'  => array( 'internal' => $internal, 'external' => $external ),
					'status' => 'ok',
				);
			}

			if ( in_array( 'readability_fk', $checks, true ) ) {
				// 簡易 Flesch-Kincaid 読みやすさ (粗い推定)。
				$text      = $content_text;
				$sentences = max( 1, preg_match_all( '/[.!?。！？]/u', $text, $m2 ) );
				$words     = max( 1, str_word_count( $text ) );
				$syllables = max( 1, substr_count( strtolower( $text ), 'a' ) + substr_count( $text, 'e' ) + substr_count( $text, 'i' ) + substr_count( $text, 'o' ) + substr_count( $text, 'u' ) ); // ラフ。
				$fk        = 206.835 - 1.015 * ( $words / $sentences ) - 84.6 * ( $syllables / $words );
				$result['readability_fk'] = array(
					'value'  => round( $fk, 1 ),
					'status' => ( $fk >= 50 ) ? 'ok' : 'warn',
				);
			}

			return array( 'checks' => $result );
		},
	) );
} );

/**
 * 人気記事リスト（WPP があれば利用、なければ最近の投稿）。
 */
add_action( 'wp_abilities_api_init', static function () {
	wp_register_ability( 'readonly-plugin/list-trending', array(
		'label'       => 'List Trending Articles',
		'description' => '人気順の記事を返します。WPP が無ければ直近記事で代替します。',
		'category'    => 'seo',
		'input_schema' => array(
			'type'       => 'object',
			'properties' => array(
				'limit'  => array(
					'type'    => 'integer',
					'minimum' => 1,
					'maximum' => 10,
					'default' => 5,
				),
				'metric' => array(
					'type'    => 'string',
					'enum'    => array( 'views_7d', 'views_30d' ),
					'default' => 'views_7d',
				),
			),
		),
		'output_schema' => array(
			'type'       => 'object',
			'properties' => array(
				'items' => array( 'type' => 'array' ),
			),
			'required' => array( 'items' ),
		),
		'meta' => array(
			'show_in_rest' => true,
			'mcp'          => array(
				'public' => true,
				'type'   => 'tool',
			),
		),
		'permission_callback' => static function () {
			return current_user_can( 'read' );
		},
		'execute_callback' => static function ( $input ) {
			$limit  = isset( $input['limit'] ) ? (int) $input['limit'] : 5;
			$metric = isset( $input['metric'] ) && in_array( $input['metric'], array( 'views_7d', 'views_30d' ), true ) ? $input['metric'] : 'views_7d';

			$items = array();

			if ( function_exists( 'wpp_get_mostpopular' ) ) {
				$range = ( 'views_30d' === $metric ) ? 'monthly' : 'weekly';
				$list  = wpp_get_mostpopular(
					array(
						'limit'      => $limit,
						'range'      => $range,
						'post_type'  => 'post',
						'freshness'  => 1,
						'stats_views'=> 1,
						'stats_date' => 1,
						'wpp_start'  => '<wpp>',
						'wpp_end'    => '</wpp>',
						'do_not_echo'=> 1,
					)
				);
				// wpp_get_mostpopular can return HTML; use get_posts style to avoid parsing HTML.
				if ( empty( $items ) && is_array( $list ) ) {
					foreach ( $list as $entry ) {
						$items[] = array(
							'id'        => (int) $entry->id,
							'title'     => $entry->title,
							'permalink' => get_permalink( (int) $entry->id ),
							'metric'    => (int) ( $entry->pageviews ?? 0 ),
							'date'      => get_the_date( DATE_ATOM, (int) $entry->id ),
						);
					}
				}
			}

			// フォールバック: 最新記事。
			if ( empty( $items ) ) {
				$q = new \WP_Query(
					array(
						'post_type'      => 'post',
						'post_status'    => 'publish',
						'posts_per_page' => $limit,
						'orderby'        => 'date',
						'order'          => 'DESC',
					)
				);
				while ( $q->have_posts() ) {
					$q->the_post();
					$post     = get_post();
					$items[] = array(
						'id'        => $post->ID,
						'title'     => get_the_title( $post ),
						'permalink' => get_permalink( $post ),
						'metric'    => null,
						'date'      => get_the_date( DATE_ATOM, $post ),
					);
				}
				wp_reset_postdata();
			}

			return array( 'items' => $items );
		},
	) );
} );

/**
 * キーワードに近い内部記事を返す能力。
 */
add_action( 'wp_abilities_api_init', static function () {
	wp_register_ability( 'readonly-plugin/keyword-gap-hints', array(
		'label'       => 'Keyword Gap Hints',
		'description' => '指定キーワードに近い内部記事を返し、内部リンク候補を提示します。',
		'category'    => 'seo',
		'input_schema' => array(
			'type'       => 'object',
			'properties' => array(
				'keyword' => array( 'type' => 'string' ),
				'limit'   => array(
					'type'    => 'integer',
					'minimum' => 1,
					'maximum' => 10,
					'default' => 5,
				),
			),
			'required' => array( 'keyword' ),
		),
		'output_schema' => array(
			'type'       => 'object',
			'properties' => array(
				'items' => array( 'type' => 'array' ),
			),
			'required' => array( 'items' ),
		),
		'meta' => array(
			'show_in_rest' => true,
			'mcp'          => array(
				'public' => true,
				'type'   => 'tool',
			),
		),
		'permission_callback' => static function () {
			return current_user_can( 'read' );
		},
		'execute_callback' => static function ( $input ) {
			$keyword = trim( (string) ( $input['keyword'] ?? '' ) );
			if ( '' === $keyword ) {
				return new \WP_Error( 'invalid_keyword', 'keyword は必須です。' );
			}
			$limit = isset( $input['limit'] ) ? (int) $input['limit'] : 5;

			$q = new \WP_Query(
				array(
					's'                 => $keyword,
					'post_type'         => 'post',
					'post_status'       => 'publish',
					'posts_per_page'    => $limit,
					'orderby'           => 'relevance',
					'ignore_sticky_posts' => true,
					'no_found_rows'     => true,
				)
			);

			$items = array();
			while ( $q->have_posts() ) {
				$q->the_post();
				$post    = get_post();
				$title   = get_the_title( $post );
				$content = wp_strip_all_tags( $post->post_content );
				// 簡易スコア: タイトル+本文中の出現回数。
				$score = substr_count( mb_strtolower( $title ), mb_strtolower( $keyword ) ) + substr_count( mb_strtolower( $content ), mb_strtolower( $keyword ) );

				$items[] = array(
					'id'        => $post->ID,
					'title'     => $title,
					'permalink' => get_permalink( $post ),
					'score'     => $score,
				);
			}
			wp_reset_postdata();

			return array( 'items' => $items );
		},
	) );
} );
